version: '3'
services:

  # App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0 --port=9000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - 9000:9000
    networks:
      - network
    depends_on:
      - database

  # Database
  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=neuco"
    ports:
      - 3306:3306
    networks:
      - network

# Networks
networks:
  network:
    driver: bridge